species: Brachypodium distachyon

seq_info:
  type: MeDIP-Seq
  mode: PE
  replicate: 1

path: /var/data/raw_data/CZQ_MeDIP_5sam_1rep/fastq

samples:
  - A
  - B
  - C
  - D
  - E
  - Input

treat:
  - A
  - B
  - C
  - D
  - E

control: Input

sample_info:
  A: 22C
  B: 37C
  C: 22C
  D: 45C
  E: 45C

index: /home/xfu/Gmatic6/genome/Bdi_v1.0/Bdi

txdb: /home/xfu/Gmatic6/gene/Bdi_v1.0/Bdi_txdb.sqlite

gene2go: /home/xfu/Gmatic6/gene/Bdi_v1.0/Bdi_gene2GOterm.tsv

cpu: 30

adapter: /home/xfu/miniconda2/envs/gmatic/share/trimmomatic/adapters/TruSeq3-PE-2.fa

insert: 1000

IGV: /home/xfu/igv/genomes/Bdi.genome
